var json_= [
    [
        "StartPage"
    ],
    [
        [
            3,
            2,
            1
        ],
        [
            "卂丂爪",
            "Oƒƒice",
            "ĐØ₵𝓼...",
            "ⓉⒺⓧⓉ",
            "S🌎cial",
            "ℝ𝕒𝕟𝕕𝕠𝕞"
        ],
        [
            4,
            4,
            4,
            4,
            4,
            4
        ],
        [
            21,
            21,
            21,
            21,
            21,
            21
        ]
    ],
    [
        [
            [
                "Nasm Doc",
                "https://www.nasm.us/doc/nasmdocb.html"
            ],
            [
                "MIPS ASM",
                "https://chortle.ccsu.edu/AssemblyTutorial/index.html"
            ],
            [
                "X86 Opcode",
                "http://ref.x86asm.net/coder64.html"
            ],
            [
                "Syscall w3chall",
                "https://syscalls.w3challs.com/"
            ],
            [
                "ASM-Basic",
                "https://www.tutorialspoint.com/assembly_programming/"
            ]
        ],
        [
            [
                "Gmail",
                "https://www.google.com/intl/en/gmail/about/"
            ],
            [
                "Notion",
                "https://www.notion.so/"
            ],
            [
                "Dillinger",
                "https://dillinger.io/"
            ],
            [
                "Draw.IO",
                "https://app.diagrams.net/"
            ]
        ],
        [
            [
                "",
                ""
            ],
            [
                "DEV-docs",
                "https://devdocs.io/settings"
            ],
            [
                "[W3]schools",
                "https://www.w3schools.com/"
            ],
            [
                "CPP",
                "http://www.cplusplus.com/reference/"
            ],
            [
                "Octave",
                "https://octave.org/doc/v6.1.0/"
            ],
            [
                "Python",
                "https://docs.python.org/3/tutorial/datastructures.html"
            ]
        ],
        [
            [
                "Unicode List",
                "https://www.isthisthingon.org/unicode/?page=0F&subpage=D"
            ],
            [
                "Fancy-Text",
                "https://nickfinder.com/fancy-text"
            ],
            [
                "Ascii Art",
                "https://ascii.co.uk/art"
            ],
            [
                "Cryptii",
                "https://cryptii.com/"
            ],
            [
                "(J)emoticons",
                "https://www.jemoticons.com/en"
            ]
        ],
        [
            [
                "Twitter",
                "https://twitter.com/twitter"
            ],
            [
                "Instagram",
                "https://www.instagram.com/instagram"
            ],
            [
                "Youtube",
                "https://www.youtube.com/"
            ],
            [
                "Facebook",
                "https://www.facebook.com/GitHub/"
            ],
            [
                "Discord",
                "https://discord.com/login"
            ],
            [
                "Reddit",
                "https://www.reddit.com/"
            ],
            [
                "GitHub",
                "https://github.com/explore"
            ]
        ],
        [
            [
                "JSON Editor",
                "https://jsoneditoronline.org/"
            ],
            [
                "FileFormat",
                "https://www.fileformat.info/index.htm"
            ],
            [
                "RosettaCode",
                "https://rosettacode.org/wiki/Category:Octave"
            ],
            [
                "Science General",
                "https://www.cs.utah.edu/~germain/PPS/Topics/"
            ],
            [
                "Desmos",
                "https://www.desmos.com/calculator"
            ],
            [
                "FlatIcon",
                "https://www.flaticon.com/"
            ],
            [
                "Instructables",
                "https://www.instructables.com/"
            ]
        ]
    ]
]